# Generated by Django 5.2.13 on 2026-04-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('canvas_data', models.JSONField(default=dict)),
                ('width', models.IntegerField(default=794)),
                ('height', models.IntegerField(default=1123)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('event', 'Événement'), ('tournament', 'Tournoi'), ('announcement', 'Annonce'), ('generic', 'Générique')], default='generic', max_length=50)),
                ('canvas_data', models.JSONField(default=dict)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
